/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SCLK.h"
#include "SCLK_aliases.h"
#include "MOSI.h"
#include "MOSI_aliases.h"
#include "UART_Putty.h"
#include "UART_Putty_SPI_UART.h"
#include "UART_Putty_PINS.h"
#include "UART_Putty_SPI_UART_PVT.h"
#include "UART_Putty_PVT.h"
#include "UART_Putty_BOOT.h"
#include "SS.h"
#include "SS_aliases.h"
#include "SPI_Slave.h"
#include "SPI_Slave_PVT.h"
#include "RX_interrupt.h"
#include "UART_Putty_SCBCLK.h"
#include "UART_Putty_tx.h"
#include "UART_Putty_tx_aliases.h"
#include "UART_Putty_rx.h"
#include "UART_Putty_rx_aliases.h"
#include "SPI_Slave_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

