/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4-dev */

#ifndef PB_INTELLIFLOW_PROTO_INTELLIFLOW_PB_H_INCLUDED
#define PB_INTELLIFLOW_PROTO_INTELLIFLOW_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _intelliflow_Sensor_units {
    intelliflow_Sensor_units_celsius = 0,
    intelliflow_Sensor_units_fahrenheit = 1,
    intelliflow_Sensor_units_bar = 2,
    intelliflow_Sensor_units_psi = 3,
    intelliflow_Sensor_units_ph = 4,
    intelliflow_Sensor_units_ppm = 5,
    intelliflow_Sensor_units_volts = 6,
    intelliflow_Sensor_units_current = 7,
    intelliflow_Sensor_units_cmps = 8,
    intelliflow_Sensor_units_timestamp = 9
} intelliflow_Sensor_units;

typedef enum _intelliflow_Admin_options {
    intelliflow_Admin_options_restart = 0,
    intelliflow_Admin_options_init = 1,
    intelliflow_Admin_options_factoryreset = 2,
    intelliflow_Admin_options_cli = 3
} intelliflow_Admin_options;

/* Struct definitions */
typedef struct _intelliflow_Hub {
    pb_callback_t id;
    pb_callback_t sensors;
} intelliflow_Hub;

typedef struct _intelliflow_Admin {
    pb_callback_t id;
    intelliflow_Admin_options option;
    pb_callback_t command;
} intelliflow_Admin;

typedef struct _intelliflow_Sensor {
    char id[128];
    double value;
    intelliflow_Sensor_units unit;
} intelliflow_Sensor;


/* Helper constants for enums */
#define _intelliflow_Sensor_units_MIN intelliflow_Sensor_units_celsius
#define _intelliflow_Sensor_units_MAX intelliflow_Sensor_units_timestamp
#define _intelliflow_Sensor_units_ARRAYSIZE ((intelliflow_Sensor_units)(intelliflow_Sensor_units_timestamp+1))

#define _intelliflow_Admin_options_MIN intelliflow_Admin_options_restart
#define _intelliflow_Admin_options_MAX intelliflow_Admin_options_cli
#define _intelliflow_Admin_options_ARRAYSIZE ((intelliflow_Admin_options)(intelliflow_Admin_options_cli+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define intelliflow_Sensor_init_default          {"", 0, _intelliflow_Sensor_units_MIN}
#define intelliflow_Hub_init_default             {{{NULL}, NULL}, {{NULL}, NULL}}
#define intelliflow_Admin_init_default           {{{NULL}, NULL}, _intelliflow_Admin_options_MIN, {{NULL}, NULL}}
#define intelliflow_Sensor_init_zero             {"", 0, _intelliflow_Sensor_units_MIN}
#define intelliflow_Hub_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}}
#define intelliflow_Admin_init_zero              {{{NULL}, NULL}, _intelliflow_Admin_options_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define intelliflow_Hub_id_tag                   1
#define intelliflow_Hub_sensors_tag              2
#define intelliflow_Admin_id_tag                 1
#define intelliflow_Admin_option_tag             2
#define intelliflow_Admin_command_tag            3
#define intelliflow_Sensor_id_tag                1
#define intelliflow_Sensor_value_tag             2
#define intelliflow_Sensor_unit_tag              3

/* Struct field encoding specification for nanopb */
#define intelliflow_Sensor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             2) \
X(a, STATIC,   SINGULAR, UENUM,    unit,              3)
#define intelliflow_Sensor_CALLBACK NULL
#define intelliflow_Sensor_DEFAULT NULL

#define intelliflow_Hub_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   sensors,           2)
#define intelliflow_Hub_CALLBACK pb_default_field_callback
#define intelliflow_Hub_DEFAULT NULL

#define intelliflow_Admin_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    option,            2) \
X(a, CALLBACK, SINGULAR, STRING,   command,           3)
#define intelliflow_Admin_CALLBACK pb_default_field_callback
#define intelliflow_Admin_DEFAULT NULL

extern const pb_msgdesc_t intelliflow_Sensor_msg;
extern const pb_msgdesc_t intelliflow_Hub_msg;
extern const pb_msgdesc_t intelliflow_Admin_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define intelliflow_Sensor_fields &intelliflow_Sensor_msg
#define intelliflow_Hub_fields &intelliflow_Hub_msg
#define intelliflow_Admin_fields &intelliflow_Admin_msg

/* Maximum encoded size of messages (where known) */
#define intelliflow_Sensor_size                  141
/* intelliflow_Hub_size depends on runtime parameters */
/* intelliflow_Admin_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
